TRAIN:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 8
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 10
  AUTO_RESUME: False
  FINE_TUNE: False
DATA:
  NUM_FRAMES: 16
  FRAMES_BETWEEN_CLIPS: 16
  FRAME_RATE: 15
  TRAIN_MIN_MAX_SCALE: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_MIN_SHORT_SIDE_SCALE: 256
  TEST_CROP_SIZE: 256
  OVERWRITE_METADATA: False
SOLVER:
  BASE_LR: 0.01
  MAX_EPOCH: 20
  T_MAX: 30
  LR_POLICY: 'cosine_linear_warmup'
  WARMUP_FACTOR: 0.1
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.94
  NESTEROV: True
  OPTIMIZING_METHOD: sgd
MODEL:
  ARCH: 'mvit_base_16x4'
  NUM_CLASSES: 20
  LOSS_FUNC: 'cross_entropy'
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 1
RNG_SEED: 0
LOG_PERIOD: 50
OUTPUT_DIR: ./experiments/kinetics
